version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudformation-base"
s3_prefix = "cloudformation-base"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6miwi01gs8e2"
